apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-storage
spec:
  capacity:
    storage: 30Gi  
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /mnt/clickhouse  